/*
 * BrowseProducts.java
 *
 * 
 */
package UserInterface.CustomerRole;

import Business.Business;
import Business.Customer;
import Business.CustomerDirectory;
import Business.MasterOrderCatalog;
import Business.Order;
import Business.OrderItem;
import Business.SalesPerson;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ayushi
 */
public class StatusOrder extends javax.swing.JPanel {

private JPanel userProcessContainer;
private Business business;
private Customer customer;

private MasterOrderCatalog masterCatalogOrder;
    /** Creates new form BrowseProducts */
    public StatusOrder(JPanel userProcessContaine,Customer customer, Business business) {
        initComponents();
       
        this.userProcessContainer = userProcessContainer;
        this.business= business;
        this.customer= customer;
        this.masterCatalogOrder = business.getMasterOrderCatalog();
        populateProductTable();
    }

   

    private void populateProductTable(){
        
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        model.setRowCount(0);
        for(Order order : masterCatalogOrder.getOrderCatalog()){
            if(customer.getCustomer_ID()==order.getCustomer().getCustomer_ID()){
            for (OrderItem oi : order.getOrderItemList()){
            Object row[] = new Object[5];
            row[0] = oi;
            row[1]= oi.getCustomerPrice();
            row[2]=oi.getQuantity();
            row[3]=oi.getProduct().getTargetPrice();
            row[4]=oi.getStatus();
            model.addRow(row);
            }
        }
    }
        
    
    }
    
    
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 511));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderJTable.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Customer Price", "Sales Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 590, 140));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jLabel2.setText("Customer Order Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 240, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel3.setText("Check Order Status");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        backJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderJTable;
    // End of variables declaration//GEN-END:variables
}
