/*
 * BrowseProducts.java
 *
 * 
 */
package UserInterface.SalesRole;

import Business.Business;
import Business.Customer;
import Business.CustomerDirectory;
import Business.MasterOrderCatalog;
import Business.Order;
import Business.OrderItem;
import Business.SalesPerson;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ayushi
 */
public class CheckorderStatus extends javax.swing.JPanel {

private JPanel userProcessContainer;
private Business business;
private SalesPerson salesPerson;
private CustomerDirectory customerDirectory;
private MasterOrderCatalog masterCatalogOrder;
    /** Creates new form BrowseProducts */
    public CheckorderStatus(JPanel userProcessContainer,SalesPerson salesPerson, Business business) {
        initComponents();
       
        this.userProcessContainer = userProcessContainer;
        this.business= business;
        this.salesPerson = salesPerson;
        this.customerDirectory = business.getCustomerDirectory();
        this.masterCatalogOrder = business.getMasterOrderCatalog();
        populateCombo();
      
    }

    private void populateCombo(){
        
        CustComboBox1.removeAllItems();
        for (Customer customer : customerDirectory.getCustomerList()){
            CustComboBox1.addItem(customer);
        }
       //populateProductTable();
      
    }

    /*private void populateProductTable(){
        
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        
        model.setRowCount(0);
        if(customer != null){
        for(Order order : masterCatalogOrder.getOrderCatalog()){
            if(customer.getCustomer_ID()==order.getCustomer().getCustomer_ID()){
                if(salesPerson.getSalesId()==order.getSalesPerson().getSalesId()){
        
            for (OrderItem oi : order.getOrderItemList()){
            Object row[] = new Object[5];
            row[0] = oi;
            row[1]= oi.getCustomerPrice();
            row[2]=oi.getQuantity();
            row[3]=oi.getProduct().getTargetPrice();
            row[4]=oi.getStatus();
            model.addRow(row);
            }
        }
    
            }    
    }
    }
    }*/
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        model.setRowCount(0);
        Customer customer = (Customer)CustComboBox1.getSelectedItem();
       if(customer != null){
        for(Order order : masterCatalogOrder.getOrderCatalog()){
            if(customer==order.getCustomer()){
                if(salesPerson==order.getSalesPerson()){
        
            for (OrderItem oi : order.getOrderItemList()){
            Object row[] = new Object[5];
            row[0] = oi;
            row[1]= oi.getCustomerPrice();
            row[2]=oi.getQuantity();
            row[3]=oi.getProduct().getTargetPrice();
            row[4]=oi.getStatus();
            model.addRow(row);
            }
        }
    
            }    
    }
       }
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        CustComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewProdjButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        approveJButton = new javax.swing.JButton();
        rejectJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 511));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Customer Price", "Sales Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 590, 140));

        CustComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustComboBox1ActionPerformed(evt);
            }
        });
        add(CustComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 250, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jLabel1.setText("Customer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        jLabel2.setText("Customer Order Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, -1));

        viewProdjButton2.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        viewProdjButton2.setText("View Product Detail");
        viewProdjButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewProdjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton2ActionPerformed(evt);
            }
        });
        add(viewProdjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel3.setText("Check Order Status");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        backJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        approveJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        approveJButton.setText("Approve");
        approveJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        approveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveJButtonActionPerformed(evt);
            }
        });
        add(approveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, -1));

        rejectJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        rejectJButton.setText("Reject");
        rejectJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rejectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJButtonActionPerformed(evt);
            }
        });
        add(rejectJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 340, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CustComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustComboBox1ActionPerformed
        // TODO add your handling code here:
        Customer customer = (Customer)CustComboBox1.getSelectedItem();
                
        DefaultTableModel model = (DefaultTableModel)orderJTable.getModel();
        model.setRowCount(0);
        if(customer != null){
        for(Order order : masterCatalogOrder.getOrderCatalog()){
            if(customer==order.getCustomer()){
                if(salesPerson==order.getSalesPerson()){
        
            for (OrderItem oi : order.getOrderItemList()){
            Object row[] = new Object[5];
            row[0] = oi;
            row[1]= oi.getCustomerPrice();
            row[2]=oi.getQuantity();
            row[3]=oi.getProduct().getTargetPrice();
            row[4]=oi.getStatus();
            model.addRow(row);
            }
        }
    
            }    
    }
    }
        
    }//GEN-LAST:event_CustComboBox1ActionPerformed

    private void viewProdjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_viewProdjButton2ActionPerformed

    private void rejectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        OrderItem orderitem;
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"Please select a row","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
               orderitem = (OrderItem)orderJTable.getValueAt(selectedRow,0);
             }
        
       if(orderitem.getStatus()!="Rejected"){
           orderitem.setStatus("Rejected");
           refreshTable();
       }
       else{
           JOptionPane.showMessageDialog(this,"Already Rejected Order","Warning", JOptionPane.WARNING_MESSAGE);
       }
      
    }//GEN-LAST:event_rejectJButtonActionPerformed

    private void approveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        OrderItem orderitem;
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this,"Please select a row","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
               orderitem = (OrderItem)orderJTable.getValueAt(selectedRow,0);
             }
        
       //if(orderitem.getStatus()!="Approved"){
           orderitem.setStatus("Approved");
           refreshTable();
      // }
      // else{
           //JOptionPane.showMessageDialog(this,"Already Approved Order","Warning", JOptionPane.WARNING_MESSAGE);
      // }
    }//GEN-LAST:event_approveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CustComboBox1;
    private javax.swing.JButton approveJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderJTable;
    private javax.swing.JButton rejectJButton;
    private javax.swing.JButton viewProdjButton2;
    // End of variables declaration//GEN-END:variables
}
