/*
 * ProductManagerWorkAreaJPanel.java
 *
 */
package UserInterface.SalesRole;

import UserInterface.CustomerRole.*;
import Business.Business;
import Business.Customer;
import Business.MasterOrderCatalog;
import Business.SalesPerson;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ayushi
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {

private JPanel userProcessContainer;
private SalesPerson salesPerson;
private Business business;



    /** Creates new form ProductManagerWorkAreaJPanel */
    public SalesWorkAreaJPanel(JPanel userProcessContainer,SalesPerson salesPerson, Business business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salesPerson=salesPerson;
        this.business = business;
        
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkSatusJButton = new javax.swing.JButton();
        CommJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("My Work Area (Sales Person Role)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        checkSatusJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        checkSatusJButton.setText("Check Order Status >>");
        checkSatusJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkSatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSatusJButtonActionPerformed(evt);
            }
        });
        add(checkSatusJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, 30));

        CommJButton.setFont(new java.awt.Font("Calibri", 3, 17)); // NOI18N
        CommJButton.setText("Check My Commission>>");
        CommJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CommJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommJButtonActionPerformed(evt);
            }
        });
        add(CommJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkSatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSatusJButtonActionPerformed
        // TODO add your handling code here:
        CheckorderStatus cos = new CheckorderStatus(userProcessContainer, salesPerson, business); 
        userProcessContainer.add("CheckOrderStatus", cos);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_checkSatusJButtonActionPerformed

    private void CommJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommJButtonActionPerformed
        // TODO add your handling code here:
        Commission com = new Commission(userProcessContainer, salesPerson, business); 
        userProcessContainer.add("CheckOrderStatus", com);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CommJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommJButton;
    private javax.swing.JButton checkSatusJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
